# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffdccb136f3dd9dc3048d7e73ada6a9cef6d1339c135f656ef4009562b59302adc17da37b7a43fde50fba1d65e6b7f338bcbc206165f276e8d8207b6e427a160

test:
  secret_key_base: 3d0ab75ecb959cfffa32d2d9543633149036bc11bfeece519cea17ab81d4b4dd6cb7b2364538d1d79833f76e828dc74cad04877b5b1bd47db13af81296aa85a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
